### ISSUE TITLE
Syntax color error

### ISSUE THREAD

**Issue by jwoertink** [slim-template/language-slim#7]
I don't remember this being an issue before, but I just noticed this today. You'll see that the first `.form-group` is white, but the other ones are the normal orange. If I add pipes to the form, or add a line break before the first form-group, then it will colorize normally.  

![screen shot 2014-11-25 at 9 13 14 am](https://cloud.githubusercontent.com/assets/2391/5187637/55ad6122-7483-11e4-9774-31aa6fd021b7.png)

**Comment by halloffame** [comment]
I'm having the same problem. It seems like it is the `do` that is making it interpret the first line as ruby instead of slim. And when I click `cmd+/` to do a comment it uses a ruby comment instead of a slim comment. I also just started having the same problem when using the sublime package https://github.com/slim-template/ruby-slim.tmbundle. Not sure if it is related.

![screen shot 2015-01-29 at 11 10 04 am](https://cloud.githubusercontent.com/assets/957859/5964272/bb266a88-a7a7-11e4-9c34-df37e75dbde2.png)

**Comment by mikemerritt** [comment]
I can confirm this issue and it is incredibly annoying. It can be fixed by putting empty ````||```` after do but that is not a workable solution. I can't pollute the codebase with a bunch of empty ````||```` all over.

![image](https://cloud.githubusercontent.com/assets/416570/14480426/844f84e4-00ee-11e6-8c07-03d437661d27.png)
